language: python
python:
  - 2.6
  - 2.7
env:
    matrix:
      - BOTO_VERSION=2.31.1
      - BOTO_VERSION=2.25.0
      - BOTO_VERSION=2.19.0
      - BOTO_VERSION=2.12.0
      - BOTO_VERSION=2.7
install:
  - pip install boto==$BOTO_VERSION
  - pip install .
  - pip install -r requirements.txt
script:
  - make test
after_success:
  - coveralls
